apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-osen
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wwsk-tenant/rhtap-demo-app/hacbs-test-project-osen@sha256:6078435e74d6693a35611569f01068e2a1c907182579057a2b8d8e2f336ab97f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
